CREATE TABLE transactions_v2 (
    id                Uint64,
    brand             Utf8,
    model             Utf8,
    year              Int32,
    mileage_kmpl      Double,
    engine_cc         Double,
    horsepower        Double,
    fuel_type         Utf8,
    transmission      Utf8,
    owner_type        Utf8,
    color             Utf8,
    city              Utf8,
    kms_driven        Uint64,
    insurance_valid   Int32,
    service_history   Int32,
    accidents         Int32,
    tax_paid          Int32,
    number_of_doors   Int32,
    seats             Int32,
    registration_age  Int32,
    price             Double,
    PRIMARY KEY (id)
);